<?php

namespace App\Services\Document;

use App\Exceptions\FileStorageException;
use App\Models\File;
use App\Models\GeneratedDocumentReport;
use App\Models\ResearchedDocument;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Throwable;

/**
 * Owns the lifecycle of private `files` rows and their stored objects.
 *
 * `files` is polymorphic with **no** foreign key on `fileable_id`, so deleting an
 * owner never removes its `files` row or the object. This is the single place
 * that stores, collects and deletes them, and every row records the disk the
 * object lives on (D-06-02), so report PDFs can live on `reports.disk` while
 * document uploads stay on the application default.
 */
final class DocumentFileManager
{
    /**
     * Store an uploaded file on the given disk (default: the app default) and
     * create its `files` row.
     *
     * The object is written first; if the row cannot be created the object is
     * removed again, so a failure never leaves an orphan file.
     *
     * @throws FileStorageException when the disk write fails
     */
    public function store(Model $owner, UploadedFile $file, string $filename, ?string $disk = null): File
    {
        $disk = $this->resolveDisk($disk);

        $path = $file->storeAs($this->directory($owner), $file->hashName(), $disk);

        if ($path === false) {
            throw FileStorageException::diskWriteFailed();
        }

        return $this->createRow($owner, $filename, $path, $disk, $file->getMimeType(), $file->getSize());
    }

    /**
     * Store generated bytes for a morph owner on the given disk and create its row.
     *
     * Object first; if the row cannot be created the object is removed again.
     *
     * @throws FileStorageException when the disk write fails
     */
    public function storePdf(Model $owner, string $pdf, string $filename, ?string $disk = null): File
    {
        $disk = $this->resolveDisk($disk);
        $path = $this->directory($owner).'/'.Str::uuid()->toString().'.pdf';

        if (Storage::disk($disk)->put($path, $pdf) === false) {
            throw FileStorageException::diskWriteFailed();
        }

        return $this->createRow($owner, $filename, $path, $disk, 'application/pdf', strlen($pdf));
    }

    /**
     * Delete one file: the stored object (best-effort, logged) then its row.
     */
    public function delete(File $file): void
    {
        $this->deleteStoredObjects([$this->objectFor($file)]);

        $file->delete();
    }

    /**
     * Collect and delete every `files` row belonging to the document or its reports.
     *
     * Must be called inside the caller's deletion transaction. The returned
     * objects are deleted from storage only after the transaction commits.
     *
     * @return list<array{disk: string, path: string}>
     */
    public function detachForDocument(ResearchedDocument $document): array
    {
        return $this->detachRows($this->filesForDocument($document));
    }

    /**
     * Collect and delete every `files` row belonging to one report (morph rows +
     * the canonical `file_id` pointer), returning the objects to delete after commit.
     *
     * @return list<array{disk: string, path: string}>
     */
    public function detachForReport(GeneratedDocumentReport $report): array
    {
        $files = File::query()
            ->where(function ($query) use ($report): void {
                $query->where(function ($query) use ($report): void {
                    $query->where('fileable_type', $report->getMorphClass())
                        ->where('fileable_id', $report->getKey());
                })->orWhere('id', $report->file_id);
            })
            ->get();

        return $this->detachRows($files);
    }

    /**
     * Delete stored objects after a DB commit. Failures are logged, never fatal:
     * the rows are already gone, so an orphan object is an operational concern.
     *
     * @param  iterable<array{disk: string, path: string}>  $objects
     */
    public function deleteStoredObjects(iterable $objects): void
    {
        foreach ($objects as $object) {
            try {
                Storage::disk($object['disk'])->delete($object['path']);
            } catch (Throwable $exception) {
                Log::warning('Failed to delete a stored file.', [
                    'disk' => $object['disk'],
                    'path' => $object['path'],
                    'exception' => $exception->getMessage(),
                ]);
            }
        }
    }

    /**
     * Delete the given rows and return the objects they pointed at.
     *
     * @param  Collection<int, File>  $files
     * @return list<array{disk: string, path: string}>
     */
    private function detachRows(Collection $files): array
    {
        $objects = $files
            ->map(fn (File $file): array => $this->objectFor($file))
            ->values()
            ->all();

        File::query()->whereIn('id', $files->pluck('id'))->delete();

        return $objects;
    }

    /**
     * The disk+path of a stored object. A null/empty disk is the only legacy case
     * (a row written before `files.disk` existed); fall back to the app default.
     *
     * @return array{disk: string, path: string}
     */
    private function objectFor(File $file): array
    {
        return [
            'disk' => $file->disk ?: (string) config('filesystems.default'),
            'path' => $file->path,
        ];
    }

    /**
     * Create the `files` row for an already-written object; on failure the object
     * is removed again.
     *
     * @throws Throwable when the row cannot be created
     */
    private function createRow(
        Model $owner,
        string $filename,
        string $path,
        string $disk,
        ?string $mimeType,
        int|false|null $size,
    ): File {
        try {
            return File::query()->create([
                'fileable_type' => $owner->getMorphClass(),
                'fileable_id' => $owner->getKey(),
                'filename' => $filename,
                'path' => $path,
                'disk' => $disk,
                'mime_type' => $mimeType,
                'size' => $size === false ? null : $size,
            ]);
        } catch (Throwable $exception) {
            Storage::disk($disk)->delete($path);

            throw $exception;
        }
    }

    /**
     * Every `files` row owned by the document or its reports (polymorphic and the
     * canonical `generated_document_reports.file_id` pointer), deduplicated.
     *
     * @return Collection<int, File>
     */
    private function filesForDocument(ResearchedDocument $document): Collection
    {
        $reportIds = $document->reports()->pluck('id');
        $reportFileIds = $document->reports()->whereNotNull('file_id')->pluck('file_id');

        $reportMorphType = (new GeneratedDocumentReport)->getMorphClass();

        return File::query()
            ->where(function ($query) use ($document, $reportIds, $reportMorphType): void {
                $query
                    ->where(function ($query) use ($document): void {
                        $query->where('fileable_type', $document->getMorphClass())
                            ->where('fileable_id', $document->getKey());
                    })
                    ->orWhere(function ($query) use ($reportIds, $reportMorphType): void {
                        $query->where('fileable_type', $reportMorphType)
                            ->whereIn('fileable_id', $reportIds);
                    });
            })
            ->orWhereIn('id', $reportFileIds->all())
            ->get();
    }

    /**
     * Morph-aware storage directory: `reports/{reportId}` for reports, the
     * existing `documents/{documentId}` layout for everything else.
     */
    private function directory(Model $owner): string
    {
        return ($owner instanceof GeneratedDocumentReport ? 'reports/' : 'documents/').$owner->getKey();
    }

    private function resolveDisk(?string $disk = null): string
    {
        return $disk ?? (string) config('filesystems.default');
    }
}
